# java -jar target/report-0.0.1-SNAPSHOT.jar

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ReportManagement
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


  datasource:
    url: jdbc:mysql://localhost:3306/db_yolo
    username: root
    password: 123@abc
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 30
          lob:
            non_contextual_creation: true


server:
  port: 8084
  servlet:
    context-path: /report


jwt:
  auth:
    converter:
      resource-id: report
      principle-attribute: preferred_username
