# java -jar target/report-0.0.1-SNAPSHOT.jar

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ReportManagement
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


  datasource:
    url: jdbc:mysql://localhost:3306/db_reportmanagement
    username: root
    password: ""
  jpa:
    # hibernate:
    #   ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 30
          lob:
            non_contextual_creation: true


server:
  port: 8084
  servlet:
    context-path: /report


jwt:
  auth:
    converter:
      resource-id: report-management
      principle-attribute: preferred_username


project:
  # assets folder
  assets:
    folder: C:/Users/Public/Documents/Report-Management
    url: http://localhost:8084/report/assets
  files:
    folder: ${project.assets.folder}/files
    # Default folder to save uploaded documents
    documents:
      upload-dir: ${project.assets.folder}/documents
      # Default folder to save uploaded document types icons
      document-type:
        icons:
          upload-dir: ${project.files.documents.upload-dir}/document-types/icons
    # Default folder to save uploaded user files
    user-files: ${project.files.folder}/user-files
    # Default folder to save uploaded images
    images:
      upload-dir: ${project.files.folder}/images
      user-profile:
        # Default folder to save uploaded users avatars
        avatars:
          upload-dir: ${project.files.images.upload-dir}/avatar
        themes:
          upload-dir: ${project.files.images.upload-dir}/theme
